# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_ymd_wrappers", use_symbols = TRUE, package_name = "ymd")

#' @docType package
#' @usage NULL
#' @useDynLib ymd, .registration = TRUE
NULL

#' Convert integers or strings to Date
#'
#' @param x an integerable or string vector in ymd format
#'
#' @return a Date object
#'
#' @export
ymd <- function(x) .Call(wrap__ymd, x)

bop <- function(x, p) .Call(wrap__bop, x, p)

eop <- function(x, p) .Call(wrap__eop, x, p)

