# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ymd_wrappers", use_symbols = TRUE, package_name = "ymd")

#' @docType package
#' @usage NULL
#' @useDynLib ymd, .registration = TRUE
NULL

rust_ymd <- function(x) .Call(wrap__rust_ymd, x)

period_begin <- function(x, unit) .Call(wrap__period_begin, x, unit)

period_end <- function(x, unit) .Call(wrap__period_end, x, unit)

#' Calculate the date before / after months
#' @param ref_date a Date vector
#' @param months the number of months that's added to `ref_date`
#' @note The function name is the same as the Excel function `EDATE()` and
#'   does the same. It returns the date that is the indicated number of months
#'   before or after the ref date.
#' @examples
#' edate(as.Date("2020-01-31"), 1)
#' ## supports 'YMD' formatted integer or string
#' edate(200131, 1)
#' edate(200229, -12)
#'
#' @export
edate <- function(ref_date, months) .Call(wrap__edate, ref_date, months)

#' @rdname date_part
#' @export
year <- function(ref_date) .Call(wrap__year, ref_date)

#' @rdname date_part
#' @export
month <- function(ref_date) .Call(wrap__month, ref_date)

#' @rdname date_part
#' @export
quarter <- function(ref_date) .Call(wrap__quarter, ref_date)

#' @rdname date_part
#' @export
isoweek <- function(ref_date) .Call(wrap__isoweek, ref_date)

#' @rdname date_part
#' @export
isowday <- function(ref_date) .Call(wrap__isowday, ref_date)

#' @rdname date_part
#' @export
wday <- function(ref_date) .Call(wrap__wday, ref_date)

#' @rdname date_part
#' @export
mday <- function(ref_date) .Call(wrap__mday, ref_date)

#' @rdname date_part
#' @export
yday <- function(ref_date) .Call(wrap__yday, ref_date)

#' Set The Panic Hook
#'
#' At the current version of extendr, when panic occurs, the error message won't
#' be redirected to R's stderr stream. This hook will hack and correct the behavior.
#' However, since the R's error throwing can only be changed in the macro level.
#' This hack is not very elegent but at least it's better than before.
#' TODO: Remove this when extendr fixes this issue.
#' @references
#' extendr discussion: https://github.com/extendr/extendr/issues/278#
#' @noRd
set_panic_hook <- function() invisible(.Call(wrap__set_panic_hook))


# nolint end
